eval `dircolors ~/.dir_colors/dircolors`
source ~/.dotfiles/.zplug/init.zsh

export NVM_LAZY_LOAD=true
zplug "lukechilds/zsh-nvm"

zplug "modules/git", from:zim
zplug "modules/history", from:zim
zplug "modules/meta", from:zim
zplug "modules/prompt", from:zim
zprompt_theme='magicmace'
zplug "modules/syntax-highlighting", from:zim

# This should be the LAST module
zplug "modules/completion", from:zim

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load --verbose
