source ~/.dotfiles/zplug/init.zsh

export NVM_LAZY_LOAD=true
zplug "lukechilds/zsh-nvm"

zplug "robbyrussell/oh-my-zsh", use:"lib/*.zsh"
zplug "plugins/git", from:oh-my-zsh

zplug "zsh-users/zsh-syntax-highlighting", defer:2

DEFAULT_USER=etienne
zplug "houjunchen/solarized-powerline", as:theme

# Install plugins if there are plugins that have not been installed
if ! zplug check; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load

export NODE_ENV=local
