#!/usr/bin/env bash

# Get the dotfiles directory's absolute path
SCRIPT_DIR="$(cd "$(dirname "$0")"; pwd -P)"
DOTFILES_DIR="$(dirname "$SCRIPT_DIR")"

# add homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# install new mac apps through `brew cask`
brew cask install sublime-text \
  google-chrome \
  flux \
  paste \
  skype \
  docker \
  intellij-idea \
  robomongo \
  ngrok

# install new packages through `brew`
brew install zsh \
  git \
  mas \
  tmux \
  p7zip \
  nginx

# set `zsh` as default shell
#chsh -s /usr/local/bin/zsh

# symlink zshrc
ln -s $SCRIPT_DIR/shell/zshrc $DOTFILES_DIR/.zshrc

#symlink gitconfig
ln -s $SCRIPT_DIR/git/gitconfig $DOTFILES_DIR/.gitconfig